In [44]:

# Import required libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

import warnings
warnings.filterwarnings('ignore')

In [45]:

df=pd.read_csv("telecom_churn_mock_data.csv")

In [46]:
print(df.shape)
df.head()

(2000, 21)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST2999,Male,0,Yes,Yes,71,No,No,No,No,...,No,No,No,No,One year,No,Electronic check,120.00,8756.02,No
1,CUST2998,Male,0,No,No,19,Yes,No,No,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,84.09,1642.44,No
2,CUST2997,Male,0,No,No,57,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,No,Electronic check,82.28,4805.18,No
3,CUST2996,Female,0,No,Yes,34,Yes,No,DSL,No internet service,...,No internet service,No,No internet service,No,Month-to-month,Yes,Mailed check,120.00,3951.13,No
4,CUST2995,Female,0,No,Yes,72,Yes,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,No,Bank transfer (automatic),74.29,5206.46,No

In [47]:
df=df.drop("CustomerID",axis=1)

In [48]:
print(df.shape)

(2000, 20)

In [49]:
print (df.columns.to_list())

['Gender', 'SeniorCitizen', 'Partner', 'Dependents', 'Tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [50]:
#df =pd.get_dummies(df,columns=['Gender', 'SeniorCitizen', 'Partner', 'Dependents',  'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',  'Churn'],dtype=int )

In [51]:
print(X.select_dtypes(include=['object']).columns)

Index(['InternetService', 'OnlineSecurity', 'OnlineBackup', 'TechSupport',
       'StreamingMovies', 'Contract', 'PaymentMethod'],
      dtype='str')

In [52]:
df['InternetService'] = df['InternetService'].map({
    'DSL': 0,
    'Fiber optic': 1,
    'No': 2
})

df['Contract'] = df['Contract'].map({
    'Month-to-month': 0,
    'One year': 1,
    'Two year': 2
})

df['PaymentMethod'] = df['PaymentMethod'].map({
    'Electronic check': 0,
    'Mailed check': 1,
    'Bank transfer (automatic)': 2,
    'Credit card (automatic)': 3
})

df['OnlineSecurity'] = df['OnlineSecurity'].map({
    'No': 0,
    'Yes': 1
})

df['OnlineBackup'] = df['OnlineBackup'].map({
    'No': 0,
    'Yes': 1
})

df['TechSupport'] = df['TechSupport'].map({
    'No': 0,
    'Yes': 1
})

df['StreamingMovies'] = df['StreamingMovies'].map({
    'No': 0,
    'Yes': 1
})

In [53]:
print(df.isnull().sum())

Gender                0
SeniorCitizen         0
Partner               0
Dependents            0
Tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity      350
OnlineBackup        343
DeviceProtection      0
TechSupport         381
StreamingTV           0
StreamingMovies     325
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          0
Churn                 0
dtype: int64

In [54]:
#after encoding it created new null values
median =df['OnlineSecurity'].median()
df['OnlineSecurity']= df['OnlineSecurity'].fillna(median)
mean = df['OnlineBackup'].mean()
df['OnlineBackup']= df['OnlineBackup'].fillna(mean)
mean1 = df['StreamingTV'].mean()
df['StreamingTV']= df['StreamingTV'].fillna(mean1)
mean2= df['TechSupport'].mean()
df['TechSupport']= df['TechSupport'].fillna(mean2)
mean3= df['StreamingMovies'].mean()
df['StreamingMovies ']= df['StreamingMovies '].fillna(mean3)
print(df.isnull().sum(), df.duplicated().sum())

TypeError: Cannot perform reduction 'mean' with string dtype

In [ ]:
df['Gender']= df['Gender'].map({'Male':0, 'Female': 1})
df['Partner']= df["Partner"].map({'Yes':1, 'No':0})
df['Dependents']= df["Dependents"].map({'Yes':1, 'No':0})
df['PhoneService']= df["PhoneService"].map({'Yes':1, 'No':0})
df['MultipleLines']= df["MultipleLines"].map({'Yes':1, 'No':0})
df['DeviceProtection']= df["DeviceProtection"].map({'Yes':1, 'No':0})
df['StreamingTV']= df["StreamingTV"].map({'Yes':1, 'No':0})
df['PaperlessBilling']= df["PaperlessBilling"].map({'Yes':1, 'No':0})
df['Churn']= df["Churn"].map({'Yes':1, 'No':0})

In [ ]:
df.head()

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,1,71,0,0.0,No,No,No,0.0,No,0.0,No,One year,0,Electronic check,120.00,8756.02,0
1,0,0,0,0,19,1,0.0,No,No,No,0.0,No,0.0,No,Month-to-month,1,Electronic check,84.09,1642.44,0
2,0,0,0,0,57,1,0.0,DSL,No,Yes,0.0,No,1.0,No,Month-to-month,0,Electronic check,82.28,4805.18,0
3,1,0,0,1,34,1,0.0,DSL,No internet service,No internet service,NaN,No,NaN,No,Month-to-month,1,Mailed check,120.00,3951.13,0
4,1,0,0,1,72,1,0.0,Fiber optic,No,No internet service,0.0,Yes,1.0,No,Month-to-month,0,Bank transfer (automatic),74.29,5206.46,0

In [ ]:
print(df.isnull().sum())

Gender                0
SeniorCitizen         0
Partner               0
Dependents            0
Tenure                0
PhoneService          0
MultipleLines       191
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection    354
TechSupport           0
StreamingTV         310
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          0
Churn                 0
dtype: int64

In [ ]:
#after encoding it created new null values
median =df['MultipleLines'].median()
df['MultipleLines']= df['MultipleLines'].fillna(median)
mean = df['DeviceProtection'].mean()
df['DeviceProtection']= df['DeviceProtection'].fillna(mean)
mean1 = df['StreamingTV'].mean()
df['StreamingTV']= df['StreamingTV'].fillna(mean1)
print(df.isnull().sum(), df.duplicated().sum())

Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64 0

In [ ]:
#now we're done with binary values we look for the unique values in each column to encode, so we can be sure no more binary
unique_of= ['PaymentMethod', 'InternetService', 'OnlineSecurity', 'TechSupport', 'StreamingMovies', 'Contract', 'OnlineBackup']
for column in unique_of:
    print(f'unique values in {column}\n', df[column].unique())

unique values in PaymentMethod
 <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
unique values in InternetService
 <StringArray>
['No', 'DSL', 'Fiber optic']
Length: 3, dtype: str
unique values in OnlineSecurity
 <StringArray>
['No', 'No internet service', 'Yes']
Length: 3, dtype: str
unique values in TechSupport
 <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
unique values in StreamingMovies
 <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
unique values in Contract
 <StringArray>
['One year', 'Month-to-month', 'Two year']
Length: 3, dtype: str
unique values in OnlineBackup
 <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [ ]:
df.head()

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,1,71,0,0.0,No,No,No,0.000000,No,0.000000,No,One year,0,Electronic check,120.00,8756.02,0
1,0,0,0,0,19,1,0.0,No,No,No,0.000000,No,0.000000,No,Month-to-month,1,Electronic check,84.09,1642.44,0
2,0,0,0,0,57,1,0.0,DSL,No,Yes,0.000000,No,1.000000,No,Month-to-month,0,Electronic check,82.28,4805.18,0
3,1,0,0,1,34,1,0.0,DSL,No internet service,No internet service,0.318955,No,0.349112,No,Month-to-month,1,Mailed check,120.00,3951.13,0
4,1,0,0,1,72,1,0.0,Fiber optic,No,No internet service,0.000000,Yes,1.000000,No,Month-to-month,0,Bank transfer (automatic),74.29,5206.46,0

In [ ]:
# X contains all input features

X = df.drop('Churn', axis=1)

# y contains the output label

y = df['Churn']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2000, 19)
y shape: (2000,)

In [ ]:
# 80% Training
# 20% Testing

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Rows :", X_train.shape[0])
print("Testing Rows  :", X_test.shape[0])

Training Rows : 1600
Testing Rows  : 400

In [ ]:
# Create Logistic Regression model

model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

In [ ]:

# Train the model

model.fit(X_train, y_train)

print("Model Trained Successfully!")

ValueError: could not convert string to float: 'DSL'

In [ ]:
# Predict churn on test data

y_pred = model.predict(X_test)

In [ ]:
# Calculate model accuracy

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 69.25%

In [ ]:
print(classification_report(
    y_test,
    y_pred,
    target_names=['Stayed', 'Churned']
))

              precision    recall  f1-score   support

      Stayed       0.71      0.94      0.81       278
     Churned       0.48      0.12      0.20       122

    accuracy                           0.69       400
   macro avg       0.60      0.53      0.50       400
weighted avg       0.64      0.69      0.62       400

In [ ]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

importance['Absolute_Value'] = importance['Coefficient'].abs()

importance = importance.sort_values(
    by='Absolute_Value',
    ascending=False
)

print("\nTop 5 Most Important Features")

print(importance[['Feature', 'Coefficient']].head(5))

Top 5 Most Important Features
           Feature  Coefficient
14        Contract    -0.429241
8   OnlineSecurity    -0.380804
5     PhoneService    -0.277270
11     TechSupport    -0.218181
3       Dependents    -0.164400

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print("accuracy",accuracy*100)

accuracy 62.0

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.69      0.77      0.73       264
        True       0.42      0.32      0.37       136

    accuracy                           0.62       400
   macro avg       0.56      0.55      0.55       400
weighted avg       0.60      0.62      0.61       400

In [55]:
# ==========================================
# STEP 1 - Import Libraries
# ==========================================

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

import warnings
warnings.filterwarnings("ignore")


# ==========================================
# STEP 2 - Load Dataset
# ==========================================

df = pd.read_csv("telecom_churn_mock_data.csv")

print(df.shape)
print(df.head())


# ==========================================
# STEP 3 - Remove CustomerID
# ==========================================

df.drop("CustomerID", axis=1, inplace=True)


# ==========================================
# STEP 4 - Encode Binary Columns
# ==========================================

df['Gender'] = df['Gender'].map({'Male':0,'Female':1})

df['Partner'] = df['Partner'].map({'No':0,'Yes':1})

df['Dependents'] = df['Dependents'].map({'No':0,'Yes':1})

df['PhoneService'] = df['PhoneService'].map({'No':0,'Yes':1})

df['PaperlessBilling'] = df['PaperlessBilling'].map({'No':0,'Yes':1})

df['Churn'] = df['Churn'].map({'No':0,'Yes':1})


# ==========================================
# STEP 5 - Encode Remaining Categorical Columns
# ==========================================

df['MultipleLines'] = df['MultipleLines'].map({
    'No':0,
    'Yes':1,
    'No phone service':2
})

df['InternetService'] = df['InternetService'].map({
    'DSL':0,
    'Fiber optic':1,
    'No':2
})

df['OnlineSecurity'] = df['OnlineSecurity'].map({
    'No':0,
    'Yes':1,
    'No internet service':2
})

df['OnlineBackup'] = df['OnlineBackup'].map({
    'No':0,
    'Yes':1,
    'No internet service':2
})

df['DeviceProtection'] = df['DeviceProtection'].map({
    'No':0,
    'Yes':1,
    'No internet service':2
})

df['TechSupport'] = df['TechSupport'].map({
    'No':0,
    'Yes':1,
    'No internet service':2
})

df['StreamingTV'] = df['StreamingTV'].map({
    'No':0,
    'Yes':1,
    'No internet service':2
})

df['StreamingMovies'] = df['StreamingMovies'].map({
    'No':0,
    'Yes':1,
    'No internet service':2
})

df['Contract'] = df['Contract'].map({
    'Month-to-month':0,
    'One year':1,
    'Two year':2
})

df['PaymentMethod'] = df['PaymentMethod'].map({
    'Electronic check':0,
    'Mailed check':1,
    'Bank transfer (automatic)':2,
    'Credit card (automatic)':3
})


# ==========================================
# STEP 6 - Check Missing Values
# ==========================================

print(df.isnull().sum())

# Remove rows with missing values if any
df.dropna(inplace=True)


# ==========================================
# STEP 7 - Select Features
# ==========================================

X = df.drop("Churn", axis=1)

y = df["Churn"]


# ==========================================
# STEP 8 - Split Dataset
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)


# ==========================================
# STEP 9 - Train Random Forest
# ==========================================

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Trained Successfully")


# ==========================================
# STEP 10 - Predict
# ==========================================

y_pred = model.predict(X_test)


# ==========================================
# STEP 11 - Accuracy
# ==========================================

accuracy = accuracy_score(y_test,y_pred)

print("Accuracy :",accuracy*100)


# ==========================================
# STEP 12 - Classification Report
# ==========================================

print(classification_report(
    y_test,
    y_pred,
    target_names=["Stayed","Churned"]
))


# ==========================================
# STEP 13 - Feature Importance
# ==========================================

importance = pd.DataFrame({

    "Feature":X.columns,

    "Importance":model.feature_importances_

})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nTop Important Features\n")

print(importance)


# ==========================================
# STEP 14 - Train Again Using Top Features
# ==========================================

top_features = importance.head(8)["Feature"].tolist()

print("\nSelected Features")

print(top_features)

X = df[top_features]

y = df["Churn"]


X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)

print("\nAccuracy Using Top Features")

print(f"{accuracy*100:.2f}%")

print(classification_report(
    y_test,
    y_pred,
    target_names=["Stayed","Churned"]
))

(2000, 21)
  CustomerID  Gender  SeniorCitizen Partner Dependents  Tenure PhoneService  \
0   CUST2999    Male              0     Yes        Yes      71           No
1   CUST2998    Male              0      No         No      19          Yes
2   CUST2997    Male              0      No         No      57          Yes
3   CUST2996  Female              0      No        Yes      34          Yes
4   CUST2995  Female              0      No        Yes      72          Yes

  MultipleLines InternetService       OnlineSecurity  ...  \
0            No              No                   No  ...
1            No              No                   No  ...
2            No             DSL                   No  ...
3            No             DSL  No internet service  ...
4            No     Fiber optic                   No  ...

      DeviceProtection TechSupport          StreamingTV StreamingMovies  \
0                   No          No                   No              No
1                   No          No                   No              No
2                   No          No                  Yes              No
3  No internet service          No  No internet service              No
4                   No         Yes                  Yes              No

         Contract PaperlessBilling              PaymentMethod MonthlyCharges  \
0        One year               No           Electronic check         120.00
1  Month-to-month              Yes           Electronic check          84.09
2  Month-to-month               No           Electronic check          82.28
3  Month-to-month              Yes               Mailed check         120.00
4  Month-to-month               No  Bank transfer (automatic)          74.29

   TotalCharges  Churn
0       8756.02     No
1       1642.44     No
2       4805.18     No
3       3951.13     No
4       5206.46     No

[5 rows x 21 columns]
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64
Model Trained Successfully
Accuracy : 69.75
              precision    recall  f1-score   support

      Stayed       0.72      0.94      0.81       278
     Churned       0.51      0.15      0.23       122

    accuracy                           0.70       400
   macro avg       0.61      0.54      0.52       400
weighted avg       0.65      0.70      0.63       400


Top Important Features

             Feature  Importance
18      TotalCharges    0.158035
17    MonthlyCharges    0.157599
4             Tenure    0.140866
16     PaymentMethod    0.061504
14          Contract    0.042286
6      MultipleLines    0.040874
10  DeviceProtection    0.038071
12       StreamingTV    0.037544
9       OnlineBackup    0.037151
13   StreamingMovies    0.036791
11       TechSupport    0.036141
7    InternetService    0.035313
8     OnlineSecurity    0.034589
15  PaperlessBilling    0.028598
0             Gender    0.027860
2            Partner    0.026759
3         Dependents    0.025156
1      SeniorCitizen    0.018050
5       PhoneService    0.016812

Selected Features
['TotalCharges', 'MonthlyCharges', 'Tenure', 'PaymentMethod', 'Contract', 'MultipleLines', 'DeviceProtection', 'StreamingTV']

Accuracy Using Top Features
65.25%
              precision    recall  f1-score   support

      Stayed       0.71      0.83      0.77       278
     Churned       0.39      0.24      0.29       122

    accuracy                           0.65       400
   macro avg       0.55      0.54      0.53       400
weighted avg       0.61      0.65      0.62       400